<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Page;
use App\Models\Post;
use App\Models\Tag;
use App\Models\User;
use Illuminate\Database\Seeder;

class DemoDataSeeder extends Seeder
{
    public function run(): void
    {
        if (Post::query()->where('slug', 'welcome-to-our-cms')->exists()) {
            $this->command?->info('Demo data already seeded. Skipping.');

            return;
        }

        $this->call(RoleSeeder::class);

        $admin = User::query()->where('email', 'admin@cms.local')->first();

        $editor = User::factory()->create([
            'name' => 'Demo Editor',
            'email' => 'editor@cms.local',
            'username' => 'demo_editor',
        ]);
        $editor->assignSingleRole('Editor');

        $author = User::factory()->create([
            'name' => 'Demo Author',
            'email' => 'author@cms.local',
            'username' => 'demo_author',
        ]);
        $author->assignSingleRole('Author');

        /** @var \Illuminate\Support\Collection<int, User> $authors */
        $authors = collect([$admin, $editor, $author])->filter()->values();

        $categories = Category::factory()->count(4)->create();
        Category::factory()->childOf($categories->first())->create();

        $tags = Tag::factory()->count(8)->create();

        Post::factory()->published()->create([
            'title' => 'Welcome to Our CMS',
            'slug' => 'welcome-to-our-cms',
            'body' => '<p>This post was generated by the demo seeder using Laravel factories. It proves the CMS backend stores content that the public frontend can read.</p><p>Edit this post in the admin panel, then refresh this page to see your changes live.</p>',
            'excerpt' => 'A sample post demonstrating that CMS content flows from the admin backend to the public frontend.',
            'author_id' => $authors->first()->id,
            'published_at' => now()->subDays(3),
        ]);

        foreach (range(1, 14) as $_) {
            Post::factory()->published()->create([
                'author_id' => $authors->random()->id,
            ]);
        }

        Post::factory()->count(3)->create(['author_id' => $author->id]);
        Post::factory()->pending()->count(2)->create(['author_id' => $author->id]);

        Post::query()
            ->where('status', \App\Enums\ContentStatus::Published)
            ->each(function (Post $post) use ($categories, $tags): void {
                $post->categories()->attach(
                    $categories->random(min(2, $categories->count()))->pluck('id')->all(),
                );
                $post->tags()->attach(
                    $tags->random(min(4, $tags->count()))->pluck('id')->all(),
                );
            });

        $aboutPage = Page::factory()->published()->inNavigation()->create([
            'title' => 'About Us',
            'slug' => 'about-us',
            'body' => '<p>We build content management tools that are powerful for editors and simple for visitors.</p><p>This page is managed entirely through the Filament admin panel.</p>',
            'author_id' => $authors->first()->id,
            'sort_order' => 0,
        ]);

        Page::factory()->published()->childOf($aboutPage)->inNavigation()->create([
            'title' => 'Our Team',
            'slug' => 'our-team',
            'body' => '<p>Meet the people behind the CMS demo content.</p>',
            'author_id' => $editor->id,
        ]);

        Page::factory()->published()->inNavigation()->create([
            'title' => 'Services',
            'slug' => 'services',
            'body' => '<p>We help teams publish and manage content with a clear workflow from draft to live.</p><p>From page building and media libraries to roles and publishing controls, our tools keep editors productive and visitors informed.</p>',
            'author_id' => $authors->random()->id,
            'sort_order' => 1,
        ]);

        Page::factory()->published()->inNavigation()->create([
            'title' => 'Contact',
            'slug' => 'contact',
            'body' => '<p>Get in touch with us — we would love to hear from you.</p><p>Reach out with questions about the CMS, feedback on the demo, or help getting started with your own content.</p>',
            'author_id' => $authors->random()->id,
            'sort_order' => 2,
        ]);

        Page::factory()->count(2)->create(['author_id' => $author->id]);

        $this->command?->info('Demo data seeded: '.Post::query()->count().' posts, '.Page::query()->count().' pages.');
    }
}
